apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: codelet-application-name
  labels:
    app: codelet-application-name
    tier: codelet-application-name
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: codelet-application-name
  template:
    metadata:
      labels:
        tier: codelet-application-name
    spec:
      containers:
        - name: codelet-application-name
          image: image:version