apiVersion: v1
kind: Pod
metadata:
    name: codelet-application
spec:
  containers:
    - name: codelet-application-name
      image: image:version
      command: ["/init/start.sh"]
      ports:
        - name: port-name
          containerPort: 8080
          protocol: TCP
      volumes:
        - name: volume-name
          mountPath: /init
  volumes:
    - name: volume-name
